/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/tPPqYjx2820
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardContent } from "@/components/ui/card"
import { TooltipProvider, Tooltip } from "@/components/ui/tooltip"
import Link from "next/link"

export function ProjectCard() {
  return (
    <Card className="w-full max-w-sm rounded-lg overflow-hidden shadow-lg transition-all duration-300 hover:shadow-2xl">
      <img
        src="/placeholder.svg"
        alt="Project Image"
        className="w-full h-48 object-cover"
        width="400"
        height="200"
        style={{ aspectRatio: "400/200", objectFit: "cover" }}
      />
      <CardContent className="p-6 space-y-4">
        <div>
          <h3 className="text-xl font-bold">Project Name</h3>
          <p className="text-muted-foreground">A brief description of the project and the technologies used.</p>
        </div>
        <div className="flex flex-wrap gap-2">
          <TooltipProvider>
            <Tooltip content="React">
              <div className="bg-muted rounded-full px-3 py-1 text-xs font-medium text-muted-foreground border-2 border-gradient-to-r from-[#ff6b6b] to-[#ffa500] rounded-full">
                React
              </div>
            </Tooltip>
            <Tooltip content="Lorem ipsum">
              <div className="bg-muted rounded-full px-3 py-1 text-xs font-medium text-muted-foreground border-2 border-gradient-to-r from-[#ff6b6b] to-[#ffa500] rounded-full">
                Tailwind CSS
              </div>
            </Tooltip>
            <Tooltip content="Node.js">
              <div className="bg-muted rounded-full px-3 py-1 text-xs font-medium text-muted-foreground border-2 border-gradient-to-r from-[#ff6b6b] to-[#ffa500] rounded-full">
                Node.js
              </div>
            </Tooltip>
            <Tooltip content="MongoDB">
              <div className="bg-muted rounded-full px-3 py-1 text-xs font-medium text-muted-foreground border-2 border-gradient-to-r from-[#ff6b6b] to-[#ffa500] rounded-full">
                MongoDB
              </div>
            </Tooltip>
          </TooltipProvider>
        </div>
        <div className="flex items-center justify-between">
          <Link
            href="#"
            className="text-primary hover:underline underline-offset-2 flex items-center gap-2"
            prefetch={false}
          >
            <GithubIcon className="w-4 h-4" />
            GitHub
          </Link>
          <Link
            href="#"
            className="text-primary hover:underline underline-offset-2 flex items-center gap-2"
            prefetch={false}
          >
            <GlobeIcon className="w-4 h-4" />
            Live
          </Link>
        </div>
      </CardContent>
    </Card>
  )
}

function GithubIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}


function GlobeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20" />
      <path d="M2 12h20" />
    </svg>
  )
}
